### ISSUE TITLE
Wrong file store_inventory_9.5.0.zip

### ISSUE THREAD

**Issue by franzholz** [TYPO3-Documentation/store_inventory#3]
store_inventory 9.5.1 contains a wrong ZIP file store_inventory_9.5.0.zip. Remove it and upload a new version 9.5.2 into TER!

**Comment by DavidBruchmann** [comment]
Is this still relevant?

**Comment by franzholz** [comment]
The wrong ZIP file is still there in 9.5.0:

https://github.com/TYPO3-Documentation/store_inventory/compare/master...9.5  

https://github.com/TYPO3-Documentation/store_inventory/blob/9.5/store_inventory_9.5.0.zip

**Comment by DavidBruchmann** [comment]
@linawolf I've no knowledge what's happening there, perhaps you can have a look?

**Comment by DavidBruchmann** [comment]
@franzholz thanks, did you check also in TER?

**Comment by linawolf** [comment]
We discontinued developing this example. Closing the issue and archiving the example
